INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (0, 0, 'Babeurre');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (1, 0, 'Benzoate de calcium');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (2, 0, 'Beurre');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (3, 0, 'Beurre concentré');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (4, 0, 'Calciumstearoylactylaat');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (5, 0, 'Caséinate');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (6, 0, 'Caséine');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (7, 0, 'Cheddar');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (8, 0, 'Concentré de lactosérum');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (9, 0, 'Concentré de protéines de lactosérum');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (10, 0, 'Cottage cheese');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (11, 0, 'Crème');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (12, 0, 'Crème chantilly');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (13, 0, 'Crème fouettée');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (14, 0, 'Crème fraiche');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (15, 0, 'E101');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (16, 0, 'E213');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (17, 0, 'E234');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (18, 0, 'E481');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (19, 0, 'E482');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (20, 0, 'E966');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (21, 0, 'Fromage');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (22, 0, 'Ghee');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (23, 0, 'Glycomacropeptide');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (24, 0, 'Grana padano');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (25, 0, 'Immunoglobuline');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (26, 0, 'Kéfir');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (27, 0, 'La glace');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (28, 0, 'Lactitol');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (29, 0, 'Lactose');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (30, 0, 'Lait');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (31, 0, 'Lait de beurre');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (32, 0, 'Lait de brebis');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (33, 0, 'Lait de chèvre');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (34, 0, 'Lait de vache');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (35, 0, 'Lait en poudre');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (36, 0, 'Lait écrémé');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (37, 0, 'Le lait écrémé en poudre');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (38, 0, 'Les solides du lait');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (39, 0, 'Margarine');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (40, 0, 'Matière grasse');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (41, 0, 'Matières grasses du lait');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (42, 0, 'Mozzarella');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (43, 0, 'Nisine');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (44, 0, 'Petit lait');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (45, 0, 'Lactosérum');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (46, 0, 'Poudre de lactosérum');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (47, 0, 'Poudre de petit lait');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (48, 0, 'Protéine de lait hydrolysée');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (49, 0, 'Protéines du lait');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (50, 0, 'Sucre du lait');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (51, 0, 'Tagatose');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (52, 0, 'Yaourt');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (53, 1, 'Albumine');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (54, 1, 'Avidine');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (55, 1, 'Blanc d\'œuf');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (56, 1, 'Blanc d\'œuf de poulet');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (57, 1, 'Conalbumine');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (58, 1, 'Des œufs');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (59, 1, 'E1105');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (60, 1, 'E322');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (61, 1, 'Gamme jaune d\'œuf de poule');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (62, 1, 'Globuline');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (63, 1, 'Jaune d\'œuf');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (64, 1, 'Lécithine');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (65, 1, 'Lipovitellin');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (66, 1, 'Livétine');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (67, 1, 'Lysozyme');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (68, 1, 'L\'écithine d\'œuf');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (69, 1, 'Mayonnaise');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (70, 1, 'Œuf');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (71, 1, 'Œuf de poules élevées en plein air');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (72, 1, 'Ovalbumine');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (73, 1, 'Ovo albumine');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (74, 1, 'Ovoglobuline');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (75, 1, 'Ovomucine');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (76, 1, 'Ovomucoïde');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (77, 1, 'Ovosucrol');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (78, 1, 'Ovotranfarine');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (79, 1, 'Phosphatidylsérine');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (80, 1, 'Phospholipides');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (81, 1, 'Phosvitine');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (82, 1, 'Poudre d\'œuf');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (83, 1, 'Poudre de protéine');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (84, 1, 'Protéine d\'œuf de poulet');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (85, 1, 'Œuf d\'animaux élevés en plein air');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (86, 2, 'E100');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (87, 2, 'E101');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (88, 2, 'E101a');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (89, 2, 'E102');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (90, 2, 'E103');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (91, 2, 'E104');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (92, 2, 'E105');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (93, 2, 'E106');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (94, 2, 'E107');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (95, 2, 'E110');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (96, 2, 'E111');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (97, 2, 'E120');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (98, 2, 'E121');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (99, 2, 'E122');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (100, 2, 'E124');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (101, 2, 'E123');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (102, 2, 'E125');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (103, 2, 'E126');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (104, 2, 'E127');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (105, 2, 'E128');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (106, 2, 'E129');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (107, 2, 'E130');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (108, 2, 'E131');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (109, 2, 'E132');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (110, 2, 'E133');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (111, 2, 'E140');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (112, 2, 'E141');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (113, 2, 'E142');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (114, 2, 'E143');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (115, 2, 'E150a');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (116, 2, 'E150b');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (117, 2, 'E150c');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (118, 2, 'E150d');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (119, 2, 'E151');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (120, 2, 'E152');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (121, 2, 'E153');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (122, 2, 'E154');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (123, 2, 'E155');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (124, 2, 'E160a');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (125, 2, 'E160b');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (126, 2, 'E160c');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (127, 2, 'E160d');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (128, 2, 'E160e');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (129, 2, 'E160f');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (130, 2, 'E161a');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (131, 2, 'E161b');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (132, 2, 'E161c');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (133, 2, 'E161d');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (134, 2, 'E161e');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (135, 2, 'E161f');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (136, 2, 'E161g');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (137, 2, 'E161h');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (138, 2, 'E161i');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (139, 2, 'E161j');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (140, 2, 'E162');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (141, 2, 'E163');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (142, 2, 'E164');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (143, 2, 'E170');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (144, 2, 'E171');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (145, 2, 'E172');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (146, 2, 'E173');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (147, 2, 'E174');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (148, 2, 'E175');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (149, 2, 'E180');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (150, 2, 'E181');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (151, 2, 'E182');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (152, 3, 'Aceite vegetal(palma)');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (153, 3, 'CetylPalmitate');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (154, 3, 'Elaeis Guineensis');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (155, 3, 'Epoxidized Palm Oil(UV cured coatings)');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (156, 3, 'EthylhexylPalmitate');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (157, 3, 'Glyceryl Strearate');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (158, 3, 'GlycerylStrearate');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (159, 3, 'Hydrated Palm Glycerides');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (160, 3, 'Hyrated Palm Glycerides');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (161, 3, 'OctylPalmitate');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (162, 3, 'Palm Fruit Oil');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (163, 3, 'Palm Kernel');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (164, 3, 'Palm Kernel Oil');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (165, 3, 'Palm Oil');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (166, 3, 'Palm Oil Kernel');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (167, 3, 'Palm Stearine');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (168, 3, 'Palmate');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (169, 3, 'Palmitate');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (170, 3, 'Acide palmitique');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (171, 3, 'Acide palmitique alcool palmitique');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (172, 3, 'Palmitoyl Oxostearamide Palmitoyl Tetrapeptide-3');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (173, 3, 'Palmitoyl tétrapeptide-3');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (174, 3, 'Palmitoyloxostearamide');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (175, 3, 'PalmitylAlchohol');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (176, 3, 'Palmoléine');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (177, 3, 'Palmoléine saponifiée');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (178, 3, 'Sodium Kernelate');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (179, 3, 'Sodium Palm Kernelate');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (180, 3, 'Sodium Palmate');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (181, 3, 'SodiumKernelate');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (182, 3, 'Acide stéarique');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (183, 3, 'Stéarine Palmitate Palmitate');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (184, 4, 'E1517');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (185, 4, 'E1518');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (186, 4, 'E153');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (187, 4, 'E160');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (188, 4, 'E161');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (189, 4, 'E304');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (190, 4, 'E312');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (191, 4, 'E322');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (192, 4, 'E325');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (193, 4, 'E326');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (194, 4, 'E327');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (195, 4, 'E341');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (196, 4, 'E387');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (197, 4, 'E422');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (198, 4, 'E430');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (199, 4, 'E431');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (200, 4, 'E432');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (201, 4, 'E433');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (202, 4, 'E434');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (203, 4, 'E435');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (204, 4, 'E436');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (205, 4, 'E442');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (206, 4, 'E470');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (207, 4, 'E471');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (208, 4, 'E472');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (209, 4, 'E473');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (210, 4, 'E474');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (211, 4, 'E475');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (212, 4, 'E477');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (213, 4, 'E478');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (214, 4, 'E479b');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (215, 4, 'E481');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (216, 4, 'E482');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (217, 4, 'E483');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (218, 4, 'E484');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (219, 4, 'E491');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (220, 4, 'E492');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (221, 4, 'E493');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (222, 4, 'E494');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (223, 4, 'E495');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (224, 4, 'E570');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (225, 4, 'E571');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (226, 4, 'E572');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (227, 4, 'E573');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (228, 4, 'E626');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (229, 4, 'E627');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (230, 4, 'E628');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (231, 4, 'E629');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (232, 4, 'E630');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (233, 4, 'E631');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (234, 4, 'E632');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (235, 4, 'E633');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (236, 4, 'E634');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (237, 4, 'E635');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (238, 4, 'E640');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (239, 4, 'E920');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (240, 4, 'E921');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (241, 5, 'Quinoa');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (242, 5, 'Sarrasin');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (243, 5, 'Farine de riz');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (244, 5, 'Farine d\'amande');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (245, 5, 'Amidon de pomme de terre');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (246, 5, 'Farine de tapioca');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (247, 5, 'Farine de noix de coco');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (248, 5, 'Farine de pois chiche');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (249, 5, 'Fécule de maïs');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (250, 5, 'Farine de sorgho');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (251, 5, 'Farine de millet');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (252, 5, 'Arrowroot');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (253, 5, 'Farine de lin');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (254, 5, 'Farine de graines de citrouille');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (255, 5, 'Farine de graines de tournesol');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (256, 5, 'Graines de chia');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (257, 5, 'Amarante');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (258, 5, 'Teff');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (259, 5, 'Son de riz');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (260, 5, 'Bicarbonate de soude');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (261, 5, 'Levure chimique');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (262, 5, 'Gomme de xanthane');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (263, 5, 'Husk de psyllium');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (264, 5, 'Substitut d\'œuf');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (265, 6, 'Tofu');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (266, 6, 'Seitan');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (267, 6, 'Tempeh');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (268, 6, 'Edamame');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (269, 6, 'Quorn');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (270, 6, 'Protéines végétales texturées (PVT)');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (271, 6, 'Pois chiches');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (272, 6, 'Lentilles');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (273, 6, 'Haricots noirs');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (274, 6, 'Haricots rouges');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (275, 6, 'Haricots cannellini');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (276, 6, 'Graines de chia');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (277, 6, 'Graines de chanvre');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (278, 6, 'Graines de lin');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (279, 6, 'Graines de citrouille');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (280, 6, 'Graines de tournesol');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (281, 6, 'Noix');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (282, 6, 'Amandes');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (283, 6, 'Noix de cajou');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (284, 6, 'Cacahuètes');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (285, 6, 'Yaourt grec');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (286, 6, 'Yaourt à la noix de coco');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (287, 6, 'Levure alimentaire');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (288, 6, 'Aubergine');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (289, 6, 'Champignons');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (290, 6, 'Courgette');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (291, 6, 'Épinards');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (292, 6, 'Chou frisé');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (293, 6, 'Poivrons');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (294, 6, 'Avocat');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (295, 6, 'Tomates');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (296, 6, 'Oignons');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (297, 6, 'Ail');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (298, 6, 'Gingembre');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (299, 7, 'Saumon');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (300, 7, 'Thon');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (301, 7, 'Crevettes');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (302, 7, 'Moules');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (303, 7, 'Huîtres');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (304, 7, 'Calmar');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (305, 7, 'Morue');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (306, 7, 'Anchois');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (307, 7, 'Truite');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (308, 7, 'Crabe');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (309, 7, 'Homard');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (310, 7, 'Palourdes');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (311, 7, 'Sardines');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (312, 7, 'Maquereau');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (313, 7, 'Huile de poisson');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (314, 7, 'Algues');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (315, 7, 'Crustacés');
INSERT INTO allergy_alert.ingredient (id, allergy_id, name) VALUES (316, 7, 'Mollusques');
